-- Sketo equipment import, 2026-10-07. Generated by build_equipment_followup.py.
-- First commit migrations/20261007020000_equipment_accessory_type.sql separately.
-- 8 candidate products, RU/EN/KZ. Existing matches are skipped IN FULL.
-- Draft/unpublished, no prices; preorder is a provisional editorial default.
-- Sources and exclusions: 20261007_equipment_followup_README.md.
-- Execute generated 20261007_equipment_followup.sql in full, outside an existing transaction.
-- Do not execute equipment_import.template.sql.

BEGIN;
SET LOCAL lock_timeout = '10s';
SET LOCAL search_path = public, pg_temp;
SELECT pg_advisory_xact_lock(hashtext('sketo:equipment-import:20261007'));

DO $preflight$
BEGIN
  IF to_regclass('public.products') IS NULL OR to_regclass('public.audit_logs') IS NULL THEN
    RAISE EXCEPTION 'Apply catalog and editor foundation migrations before this import.';
  END IF;
  IF EXISTS (
    SELECT 1 FROM (VALUES
      ('locale','kz'), ('equipment_brand','nuova-simonelli'),
      ('equipment_brand','eureka'), ('equipment_brand','modbar'),
      ('equipment_brand','puqpress'), ('equipment_type','tamper'),
      ('equipment_type','steam-module'), ('equipment_type','accessory')
    ) AS required(type_name,label)
    WHERE NOT EXISTS (
      SELECT 1 FROM pg_enum e JOIN pg_type t ON t.oid=e.enumtypid
      JOIN pg_namespace n ON n.oid=t.typnamespace
      WHERE n.nspname='public' AND t.typname=required.type_name AND e.enumlabel=required.label
    )
  ) THEN
    RAISE EXCEPTION 'Apply and COMMIT 20261007020000_equipment_accessory_type.sql and the KZ locale migration first.';
  END IF;
END;
$preflight$;

CREATE TEMP TABLE sketo_equipment_source ON COMMIT DROP AS
SELECT value AS data, ordinality AS position
FROM jsonb_array_elements($equipment$
[
  {
    "slug": "la-marzocco-kb90",
    "name": "KB90",
    "brand": "la-marzocco",
    "equipment_type": "espresso-machine",
    "aliases": [
      "kb90",
      "lamarzoccokb90"
    ],
    "translations": {
      "ru": {
        "name": "KB90",
        "description": "Профессиональная серия с прямой установкой портафильтра и независимыми кофейными бойлерами. Для быстрого обслуживания в загруженном баре.",
        "category": "Коммерческая кофемашина",
        "status_label": "Под заказ",
        "seo_title": "KB90 | Sketo",
        "seo_description": "Профессиональная серия с прямой установкой портафильтра и независимыми кофейными бойлерами. Для быстрого обслуживания в загруженном баре.",
        "details": [
          {
            "label": "Бренд",
            "value": "La Marzocco"
          },
          {
            "label": "Серия",
            "value": "KB90"
          },
          {
            "label": "Варианты исполнения",
            "value": "2 или 3 группы"
          },
          {
            "label": "Назначение",
            "value": "Эспрессо"
          }
        ],
        "specifications": [
          {
            "label": "Высота",
            "value": "450 мм"
          },
          {
            "label": "Ширина",
            "value": "2 группы: 810 мм; 3 группы: 1050 мм"
          },
          {
            "label": "Глубина",
            "value": "620 мм"
          },
          {
            "label": "Вес",
            "value": "2 группы: 77 кг; 3 группы: 101 кг"
          },
          {
            "label": "Мощность",
            "value": "2 группы: 5700 Вт; 3 группы: 7800 Вт (220/380 В)"
          },
          {
            "label": "Кофейные бойлеры",
            "value": "2 группы: 2 × 1.3 л; 3 группы: 3 × 1.3 л"
          },
          {
            "label": "Паровой бойлер",
            "value": "2 группы: 7 л; 3 группы: 11 л"
          }
        ],
        "features": [
          {
            "title": "Straight-In",
            "description": "Портафильтр устанавливается без поворота рукоятки."
          },
          {
            "title": "Steam Flush",
            "description": "Пар и вода промывают группу после приготовления."
          },
          {
            "title": "PID",
            "description": "Электронная регулировка температуры заваривания."
          },
          {
            "title": "независимые бойлеры",
            "description": "Отдельная температура для каждой группы."
          }
        ]
      },
      "en": {
        "name": "KB90",
        "description": "A commercial range with straight-in portafilters and independent coffee boilers for busy café service.",
        "category": "Commercial espresso machine",
        "status_label": "On request",
        "seo_title": "KB90 | Sketo",
        "seo_description": "A commercial range with straight-in portafilters and independent coffee boilers for busy café service.",
        "details": [
          {
            "label": "Brand",
            "value": "La Marzocco"
          },
          {
            "label": "Series",
            "value": "KB90"
          },
          {
            "label": "Available configurations",
            "value": "2 or 3 groups"
          },
          {
            "label": "Application",
            "value": "Espresso"
          }
        ],
        "specifications": [
          {
            "label": "Height",
            "value": "450 mm"
          },
          {
            "label": "Width",
            "value": "2 groups: 810 mm; 3 groups: 1050 mm"
          },
          {
            "label": "Depth",
            "value": "620 mm"
          },
          {
            "label": "Weight",
            "value": "2 groups: 77 kg; 3 groups: 101 kg"
          },
          {
            "label": "Power",
            "value": "2 groups: 5700 W; 3 groups: 7800 W (220/380 V)"
          },
          {
            "label": "Coffee boilers",
            "value": "2 groups: 2 × 1.3 L; 3 groups: 3 × 1.3 L"
          },
          {
            "label": "Steam boiler",
            "value": "2 groups: 7 L; 3 groups: 11 L"
          }
        ],
        "features": [
          {
            "title": "Straight-In",
            "description": "Insert the portafilter without twisting the handle."
          },
          {
            "title": "Steam Flush",
            "description": "Steam and water rinse the group after brewing."
          },
          {
            "title": "PID",
            "description": "Electronic brewing temperature control."
          },
          {
            "title": "independent boilers",
            "description": "Set each group temperature separately."
          }
        ]
      },
      "kz": {
        "name": "KB90",
        "description": "Портафильтрі тікелей орнатылатын, тәуелсіз кофе бойлерлері бар кәсіби серия. Қарқынды қызмет көрсетуге арналған.",
        "category": "Кәсіби кофемашина",
        "status_label": "Тапсырыспен",
        "seo_title": "KB90 | Sketo",
        "seo_description": "Портафильтрі тікелей орнатылатын, тәуелсіз кофе бойлерлері бар кәсіби серия. Қарқынды қызмет көрсетуге арналған.",
        "details": [
          {
            "label": "Бренд",
            "value": "La Marzocco"
          },
          {
            "label": "Сериясы",
            "value": "KB90"
          },
          {
            "label": "Орындалу нұсқалары",
            "value": "2 немесе 3 топ"
          },
          {
            "label": "Мақсаты",
            "value": "Эспрессо"
          }
        ],
        "specifications": [
          {
            "label": "Биіктігі",
            "value": "450 мм"
          },
          {
            "label": "Ені",
            "value": "2 топ: 810 мм; 3 топ: 1050 мм"
          },
          {
            "label": "Тереңдігі",
            "value": "620 мм"
          },
          {
            "label": "Салмағы",
            "value": "2 топ: 77 кг; 3 топ: 101 кг"
          },
          {
            "label": "Қуаты",
            "value": "2 топ: 5700 Вт; 3 топ: 7800 Вт (220/380 В)"
          },
          {
            "label": "Кофе бойлерлері",
            "value": "2 топ: 2 × 1.3 л; 3 топ: 3 × 1.3 л"
          },
          {
            "label": "Бу бойлері",
            "value": "2 топ: 7 л; 3 топ: 11 л"
          }
        ],
        "features": [
          {
            "title": "Straight-In",
            "description": "Портафильтр тұтқаны бұрамай орнатылады."
          },
          {
            "title": "Steam Flush",
            "description": "Дайындаудан кейін бу мен су топты шаяды."
          },
          {
            "title": "PID",
            "description": "Демдеу температурасын электронды реттеу."
          },
          {
            "title": "тәуелсіз бойлерлер",
            "description": "Әр топтың температурасы бөлек реттеледі."
          }
        ]
      }
    },
    "sources": [
      "https://au.lamarzocco.com/wp-content/uploads/2024/02/data_sheet_KB90-EN.pdf",
      "https://www.lamarzocco.com/fr/en/commercial-products/espresso-machines/kb90/"
    ],
    "document": "Уточнения пользователя от 07.10.2026",
    "note": "Серия, не конкретная 2GR/3GR или AV/ABR. Ширина 3GR 1050 мм — по указанному официальному PDF. ABR не объявлен стандартом."
  },
  {
    "slug": "mahlkonig-e65w-gbs",
    "name": "E65W GbS",
    "brand": "mahlkonig",
    "equipment_type": "grinder",
    "aliases": [
      "e65gbs",
      "e65wgbs",
      "mahlkonige65gbs",
      "mahlkonige65wgbs"
    ],
    "translations": {
      "ru": {
        "name": "E65W GbS",
        "description": "Эспрессо-кофемолка с дозированием по весу и электрической регулировкой помола. Система Sync связывает её с совместимым оборудованием.",
        "category": "Кофемолка",
        "status_label": "Под заказ",
        "seo_title": "E65W GbS | Sketo",
        "seo_description": "Эспрессо-кофемолка с дозированием по весу и электрической регулировкой помола. Система Sync связывает её с совместимым оборудованием.",
        "details": [
          {
            "label": "Бренд",
            "value": "Mahlkönig"
          },
          {
            "label": "Серия",
            "value": "E65W GbS"
          },
          {
            "label": "Тип жерновов",
            "value": "Плоские"
          },
          {
            "label": "Управление",
            "value": "Дозирование по весу"
          }
        ],
        "specifications": [
          {
            "label": "Высота",
            "value": "620 мм"
          },
          {
            "label": "Ширина",
            "value": "195 мм"
          },
          {
            "label": "Глубина",
            "value": "283 мм"
          },
          {
            "label": "Вес",
            "value": "12.2 кг"
          },
          {
            "label": "Мощность (220–240 В, 50 Гц)",
            "value": "440 Вт"
          },
          {
            "label": "Диаметр жерновов",
            "value": "65 мм"
          },
          {
            "label": "Бункер зерна",
            "value": "1200 г"
          },
          {
            "label": "Обороты (50 Гц)",
            "value": "1400 об/мин"
          }
        ],
        "features": [
          {
            "title": "дозирование по весу",
            "description": "Встроенные весы контролируют массу порции при помоле."
          },
          {
            "title": "Grind-by-Sync",
            "description": "Синхронизация с совместимой машиной или Sync-устройством."
          },
          {
            "title": "электрическая регулировка",
            "description": "Мотор изменяет расстояние между жерновами."
          },
          {
            "title": "калибровка нуля",
            "description": "Настройка с экрана без инструментов."
          }
        ]
      },
      "en": {
        "name": "E65W GbS",
        "description": "An espresso grinder with weight-based dosing, electric grind adjustment and Sync connectivity for compatible equipment.",
        "category": "Coffee grinder",
        "status_label": "On request",
        "seo_title": "E65W GbS | Sketo",
        "seo_description": "An espresso grinder with weight-based dosing, electric grind adjustment and Sync connectivity for compatible equipment.",
        "details": [
          {
            "label": "Brand",
            "value": "Mahlkönig"
          },
          {
            "label": "Series",
            "value": "E65W GbS"
          },
          {
            "label": "Burr type",
            "value": "Flat"
          },
          {
            "label": "Control",
            "value": "Weight-based dosing"
          }
        ],
        "specifications": [
          {
            "label": "Height",
            "value": "620 mm"
          },
          {
            "label": "Width",
            "value": "195 mm"
          },
          {
            "label": "Depth",
            "value": "283 mm"
          },
          {
            "label": "Weight",
            "value": "12.2 kg"
          },
          {
            "label": "Power (220–240 V, 50 Hz)",
            "value": "440 W"
          },
          {
            "label": "Burr diameter",
            "value": "65 mm"
          },
          {
            "label": "Bean hopper",
            "value": "1200 g"
          },
          {
            "label": "Speed (50 Hz)",
            "value": "1400 rpm"
          }
        ],
        "features": [
          {
            "title": "grind by weight",
            "description": "Integrated scales monitor the dose during grinding."
          },
          {
            "title": "Grind-by-Sync",
            "description": "Synchronizes with a compatible machine or Sync device."
          },
          {
            "title": "electric adjustment",
            "description": "A motor adjusts the burr spacing."
          },
          {
            "title": "zero calibration",
            "description": "Calibrate from the display without tools."
          }
        ]
      },
      "kz": {
        "name": "E65W GbS",
        "description": "Салмақ бойынша мөлшерлейтін, ұнтақтауы электрмен реттелетін эспрессо тартқышы. Sync жүйесі үйлесімді жабдықпен байланыстырады.",
        "category": "Кофе тартқыш",
        "status_label": "Тапсырыспен",
        "seo_title": "E65W GbS | Sketo",
        "seo_description": "Салмақ бойынша мөлшерлейтін, ұнтақтауы электрмен реттелетін эспрессо тартқышы. Sync жүйесі үйлесімді жабдықпен байланыстырады.",
        "details": [
          {
            "label": "Бренд",
            "value": "Mahlkönig"
          },
          {
            "label": "Сериясы",
            "value": "E65W GbS"
          },
          {
            "label": "Диірмен тастарының түрі",
            "value": "Жалпақ"
          },
          {
            "label": "Басқару",
            "value": "Салмақ бойынша мөлшерлеу"
          }
        ],
        "specifications": [
          {
            "label": "Биіктігі",
            "value": "620 мм"
          },
          {
            "label": "Ені",
            "value": "195 мм"
          },
          {
            "label": "Тереңдігі",
            "value": "283 мм"
          },
          {
            "label": "Салмағы",
            "value": "12.2 кг"
          },
          {
            "label": "Қуаты (220–240 В, 50 Гц)",
            "value": "440 Вт"
          },
          {
            "label": "Диірмен тастарының диаметрі",
            "value": "65 мм"
          },
          {
            "label": "Дән бункері",
            "value": "1200 г"
          },
          {
            "label": "Айналымы (50 Гц)",
            "value": "1400 айн/мин"
          }
        ],
        "features": [
          {
            "title": "салмақ бойынша мөлшерлеу",
            "description": "Кіріктірілген таразы ұнтақтау кезінде мөлшер салмағын бақылайды."
          },
          {
            "title": "Grind-by-Sync",
            "description": "Үйлесімді машинамен немесе Sync құрылғысымен синхрондалады."
          },
          {
            "title": "электрлік реттеу",
            "description": "Мотор диірмен тастарының арақашықтығын реттейді."
          },
          {
            "title": "нөлді калибрлеу",
            "description": "Құралсыз экран арқылы калибрленеді."
          }
        ]
      }
    },
    "sources": [
      "https://www.mahlkoenig.com/products/e65w-grind-by-sync"
    ],
    "document": "Уточнения пользователя от 07.10.2026",
    "note": "GbS подтверждено ссылкой пользователя. E80W GbS не является ранее добавленной E80S GbW. Электрические параметры для 220–240 В / 50 Гц."
  },
  {
    "slug": "mahlkonig-e80w-gbs",
    "name": "E80W GbS",
    "brand": "mahlkonig",
    "equipment_type": "grinder",
    "aliases": [
      "e80gbs",
      "e80wgbs",
      "mahlkonige80gbs",
      "mahlkonige80wgbs"
    ],
    "translations": {
      "ru": {
        "name": "E80W GbS",
        "description": "Эспрессо-кофемолка с дозированием по весу и электрической регулировкой помола. Система Sync связывает её с совместимым оборудованием.",
        "category": "Кофемолка",
        "status_label": "Под заказ",
        "seo_title": "E80W GbS | Sketo",
        "seo_description": "Эспрессо-кофемолка с дозированием по весу и электрической регулировкой помола. Система Sync связывает её с совместимым оборудованием.",
        "details": [
          {
            "label": "Бренд",
            "value": "Mahlkönig"
          },
          {
            "label": "Серия",
            "value": "E80W GbS"
          },
          {
            "label": "Тип жерновов",
            "value": "Плоские"
          },
          {
            "label": "Управление",
            "value": "Дозирование по весу"
          }
        ],
        "specifications": [
          {
            "label": "Высота",
            "value": "630 мм"
          },
          {
            "label": "Ширина",
            "value": "240 мм"
          },
          {
            "label": "Глубина",
            "value": "340 мм"
          },
          {
            "label": "Вес",
            "value": "18 кг"
          },
          {
            "label": "Мощность (220–240 В, 50 Гц)",
            "value": "520 Вт"
          },
          {
            "label": "Диаметр жерновов",
            "value": "80 мм"
          },
          {
            "label": "Бункер зерна",
            "value": "1800 г"
          },
          {
            "label": "Обороты (50 Гц)",
            "value": "1400 об/мин"
          }
        ],
        "features": [
          {
            "title": "дозирование по весу",
            "description": "Встроенные весы контролируют массу порции при помоле."
          },
          {
            "title": "Grind-by-Sync",
            "description": "Синхронизация с совместимой машиной или Sync-устройством."
          },
          {
            "title": "электрическая регулировка",
            "description": "Мотор изменяет расстояние между жерновами."
          },
          {
            "title": "калибровка нуля",
            "description": "Настройка с экрана без инструментов."
          }
        ]
      },
      "en": {
        "name": "E80W GbS",
        "description": "An espresso grinder with weight-based dosing, electric grind adjustment and Sync connectivity for compatible equipment.",
        "category": "Coffee grinder",
        "status_label": "On request",
        "seo_title": "E80W GbS | Sketo",
        "seo_description": "An espresso grinder with weight-based dosing, electric grind adjustment and Sync connectivity for compatible equipment.",
        "details": [
          {
            "label": "Brand",
            "value": "Mahlkönig"
          },
          {
            "label": "Series",
            "value": "E80W GbS"
          },
          {
            "label": "Burr type",
            "value": "Flat"
          },
          {
            "label": "Control",
            "value": "Weight-based dosing"
          }
        ],
        "specifications": [
          {
            "label": "Height",
            "value": "630 mm"
          },
          {
            "label": "Width",
            "value": "240 mm"
          },
          {
            "label": "Depth",
            "value": "340 mm"
          },
          {
            "label": "Weight",
            "value": "18 kg"
          },
          {
            "label": "Power (220–240 V, 50 Hz)",
            "value": "520 W"
          },
          {
            "label": "Burr diameter",
            "value": "80 mm"
          },
          {
            "label": "Bean hopper",
            "value": "1800 g"
          },
          {
            "label": "Speed (50 Hz)",
            "value": "1400 rpm"
          }
        ],
        "features": [
          {
            "title": "grind by weight",
            "description": "Integrated scales monitor the dose during grinding."
          },
          {
            "title": "Grind-by-Sync",
            "description": "Synchronizes with a compatible machine or Sync device."
          },
          {
            "title": "electric adjustment",
            "description": "A motor adjusts the burr spacing."
          },
          {
            "title": "zero calibration",
            "description": "Calibrate from the display without tools."
          }
        ]
      },
      "kz": {
        "name": "E80W GbS",
        "description": "Салмақ бойынша мөлшерлейтін, ұнтақтауы электрмен реттелетін эспрессо тартқышы. Sync жүйесі үйлесімді жабдықпен байланыстырады.",
        "category": "Кофе тартқыш",
        "status_label": "Тапсырыспен",
        "seo_title": "E80W GbS | Sketo",
        "seo_description": "Салмақ бойынша мөлшерлейтін, ұнтақтауы электрмен реттелетін эспрессо тартқышы. Sync жүйесі үйлесімді жабдықпен байланыстырады.",
        "details": [
          {
            "label": "Бренд",
            "value": "Mahlkönig"
          },
          {
            "label": "Сериясы",
            "value": "E80W GbS"
          },
          {
            "label": "Диірмен тастарының түрі",
            "value": "Жалпақ"
          },
          {
            "label": "Басқару",
            "value": "Салмақ бойынша мөлшерлеу"
          }
        ],
        "specifications": [
          {
            "label": "Биіктігі",
            "value": "630 мм"
          },
          {
            "label": "Ені",
            "value": "240 мм"
          },
          {
            "label": "Тереңдігі",
            "value": "340 мм"
          },
          {
            "label": "Салмағы",
            "value": "18 кг"
          },
          {
            "label": "Қуаты (220–240 В, 50 Гц)",
            "value": "520 Вт"
          },
          {
            "label": "Диірмен тастарының диаметрі",
            "value": "80 мм"
          },
          {
            "label": "Дән бункері",
            "value": "1800 г"
          },
          {
            "label": "Айналымы (50 Гц)",
            "value": "1400 айн/мин"
          }
        ],
        "features": [
          {
            "title": "салмақ бойынша мөлшерлеу",
            "description": "Кіріктірілген таразы ұнтақтау кезінде мөлшер салмағын бақылайды."
          },
          {
            "title": "Grind-by-Sync",
            "description": "Үйлесімді машинамен немесе Sync құрылғысымен синхрондалады."
          },
          {
            "title": "электрлік реттеу",
            "description": "Мотор диірмен тастарының арақашықтығын реттейді."
          },
          {
            "title": "нөлді калибрлеу",
            "description": "Құралсыз экран арқылы калибрленеді."
          }
        ]
      }
    },
    "sources": [
      "https://www.mahlkoenig.com/products/e80w-grind-by-sync"
    ],
    "document": "Уточнения пользователя от 07.10.2026",
    "note": "GbS подтверждено ссылкой пользователя. E80W GbS не является ранее добавленной E80S GbW. Электрические параметры для 220–240 В / 50 Гц."
  },
  {
    "slug": "victoria-arduino-eagle-one-2-group",
    "name": "Eagle One 2 Group",
    "brand": "victoria-arduino",
    "equipment_type": "espresso-machine",
    "aliases": [
      "eagleone2group",
      "victoriaarduinoeagleone",
      "victoriaarduinoeagleone2group"
    ],
    "translations": {
      "ru": {
        "name": "Eagle One 2 Group",
        "description": "Двухгрупповая кофемашина с системой нагрева NEO и сенсорным управлением. Компактный корпус подходит для открытой кофейной стойки.",
        "category": "Коммерческая кофемашина",
        "status_label": "Под заказ",
        "seo_title": "Eagle One 2 Group | Sketo",
        "seo_description": "Двухгрупповая кофемашина с системой нагрева NEO и сенсорным управлением. Компактный корпус подходит для открытой кофейной стойки.",
        "details": [
          {
            "label": "Бренд",
            "value": "Victoria Arduino"
          },
          {
            "label": "Серия",
            "value": "Eagle One"
          },
          {
            "label": "Группы",
            "value": "2"
          },
          {
            "label": "Назначение",
            "value": "Эспрессо"
          }
        ],
        "specifications": [
          {
            "label": "Высота",
            "value": "437 мм"
          },
          {
            "label": "Ширина",
            "value": "758 мм"
          },
          {
            "label": "Глубина",
            "value": "576 мм"
          },
          {
            "label": "Мощность",
            "value": "5000 Вт"
          },
          {
            "label": "Группы",
            "value": "2"
          }
        ],
        "features": [
          {
            "title": "NEO",
            "description": "Нагревает необходимый для приготовления объём воды."
          },
          {
            "title": "TERS",
            "description": "Возвращает тепло отработанной воды для предварительного нагрева."
          },
          {
            "title": "сенсорное управление",
            "description": "Экран упрощает выбор рецепта и настройку."
          },
          {
            "title": "Cool Touch",
            "description": "Изолированные паровые трубки удобны при работе с молоком."
          }
        ]
      },
      "en": {
        "name": "Eagle One 2 Group",
        "description": "A two-group machine with NEO heating and touch controls in a compact body for an open coffee bar.",
        "category": "Commercial espresso machine",
        "status_label": "On request",
        "seo_title": "Eagle One 2 Group | Sketo",
        "seo_description": "A two-group machine with NEO heating and touch controls in a compact body for an open coffee bar.",
        "details": [
          {
            "label": "Brand",
            "value": "Victoria Arduino"
          },
          {
            "label": "Series",
            "value": "Eagle One"
          },
          {
            "label": "Groups",
            "value": "2"
          },
          {
            "label": "Application",
            "value": "Espresso"
          }
        ],
        "specifications": [
          {
            "label": "Height",
            "value": "437 mm"
          },
          {
            "label": "Width",
            "value": "758 mm"
          },
          {
            "label": "Depth",
            "value": "576 mm"
          },
          {
            "label": "Power",
            "value": "5000 W"
          },
          {
            "label": "Groups",
            "value": "2"
          }
        ],
        "features": [
          {
            "title": "NEO",
            "description": "Heats the water needed for brewing."
          },
          {
            "title": "TERS",
            "description": "Recovers heat from waste water for preheating."
          },
          {
            "title": "touch controls",
            "description": "The screen simplifies recipe selection and setup."
          },
          {
            "title": "Cool Touch",
            "description": "Insulated steam wands support milk preparation."
          }
        ]
      },
      "kz": {
        "name": "Eagle One 2 Group",
        "description": "NEO жылыту жүйесі және сенсорлық басқаруы бар екі топты кофемашина. Ықшам корпусы ашық кофе барына ыңғайлы.",
        "category": "Кәсіби кофемашина",
        "status_label": "Тапсырыспен",
        "seo_title": "Eagle One 2 Group | Sketo",
        "seo_description": "NEO жылыту жүйесі және сенсорлық басқаруы бар екі топты кофемашина. Ықшам корпусы ашық кофе барына ыңғайлы.",
        "details": [
          {
            "label": "Бренд",
            "value": "Victoria Arduino"
          },
          {
            "label": "Сериясы",
            "value": "Eagle One"
          },
          {
            "label": "Топ саны",
            "value": "2"
          },
          {
            "label": "Мақсаты",
            "value": "Эспрессо"
          }
        ],
        "specifications": [
          {
            "label": "Биіктігі",
            "value": "437 мм"
          },
          {
            "label": "Ені",
            "value": "758 мм"
          },
          {
            "label": "Тереңдігі",
            "value": "576 мм"
          },
          {
            "label": "Қуаты",
            "value": "5000 Вт"
          },
          {
            "label": "Топ саны",
            "value": "2"
          }
        ],
        "features": [
          {
            "title": "NEO",
            "description": "Демдеуге қажетті су көлемін қыздырады."
          },
          {
            "title": "TERS",
            "description": "Алдын ала қыздыру үшін пайдаланылған судың жылуын қайта қолданады."
          },
          {
            "title": "сенсорлық басқару",
            "description": "Экран рецепт таңдауды және баптауды жеңілдетеді."
          },
          {
            "title": "Cool Touch",
            "description": "Оқшауланған бу түтіктері сүтпен жұмысқа ыңғайлы."
          }
        ]
      }
    },
    "sources": [
      "https://victoriaarduino.com/en/products-machines/eagle-one/"
    ],
    "document": "Уточнения пользователя от 07.10.2026",
    "note": "2 группы подтверждены пользователем. Данные текущей официальной страницы. EasyCream и VIS не включены без подтверждения комплектации; вес/бойлеры не выдуманы."
  },
  {
    "slug": "victoria-arduino-eagle-tempo-neo-2-group",
    "name": "Eagle Tempo Neo 2 Group",
    "brand": "victoria-arduino",
    "equipment_type": "espresso-machine",
    "aliases": [
      "eagletempo2gr",
      "eagletemponeo2group",
      "victoriaarduinoeagletempo2gr",
      "victoriaarduinoeagletemponeo2group"
    ],
    "translations": {
      "ru": {
        "name": "Eagle Tempo Neo 2 Group",
        "description": "Двухгрупповая Eagle Tempo Neo с многобойлерной системой нагрева и цифровым управлением. Для последовательного приготовления кофе и молочных напитков.",
        "category": "Коммерческая кофемашина",
        "status_label": "Под заказ",
        "seo_title": "Eagle Tempo Neo 2 Group | Sketo",
        "seo_description": "Двухгрупповая Eagle Tempo Neo с многобойлерной системой нагрева и цифровым управлением. Для последовательного приготовления кофе и молочных напитков.",
        "details": [
          {
            "label": "Бренд",
            "value": "Victoria Arduino"
          },
          {
            "label": "Серия",
            "value": "Eagle Tempo Neo"
          },
          {
            "label": "Группы",
            "value": "2"
          },
          {
            "label": "Назначение",
            "value": "Эспрессо"
          }
        ],
        "specifications": [
          {
            "label": "Высота",
            "value": "416 мм"
          },
          {
            "label": "Ширина",
            "value": "825 мм"
          },
          {
            "label": "Глубина",
            "value": "650 мм"
          },
          {
            "label": "Вес",
            "value": "62 кг"
          },
          {
            "label": "Система нагрева",
            "value": "NEO"
          }
        ],
        "features": [
          {
            "title": "NEO",
            "description": "Нагревает необходимый для приготовления объём воды."
          },
          {
            "title": "сенсорное управление",
            "description": "Экран упрощает выбор рецепта и настройку."
          },
          {
            "title": "автоматическая промывка",
            "description": "Промывка помогает поддерживать рабочий цикл."
          },
          {
            "title": "подсветка групп",
            "description": "Освещает рабочую область перед группами."
          }
        ]
      },
      "en": {
        "name": "Eagle Tempo Neo 2 Group",
        "description": "A two-group Eagle Tempo Neo with multi-boiler heating and digital controls for coffee and milk drinks.",
        "category": "Commercial espresso machine",
        "status_label": "On request",
        "seo_title": "Eagle Tempo Neo 2 Group | Sketo",
        "seo_description": "A two-group Eagle Tempo Neo with multi-boiler heating and digital controls for coffee and milk drinks.",
        "details": [
          {
            "label": "Brand",
            "value": "Victoria Arduino"
          },
          {
            "label": "Series",
            "value": "Eagle Tempo Neo"
          },
          {
            "label": "Groups",
            "value": "2"
          },
          {
            "label": "Application",
            "value": "Espresso"
          }
        ],
        "specifications": [
          {
            "label": "Height",
            "value": "416 mm"
          },
          {
            "label": "Width",
            "value": "825 mm"
          },
          {
            "label": "Depth",
            "value": "650 mm"
          },
          {
            "label": "Weight",
            "value": "62 kg"
          },
          {
            "label": "Heating system",
            "value": "NEO"
          }
        ],
        "features": [
          {
            "title": "NEO",
            "description": "Heats the water needed for brewing."
          },
          {
            "title": "touch controls",
            "description": "The screen simplifies recipe selection and setup."
          },
          {
            "title": "automatic purge",
            "description": "Automatic purging supports the service workflow."
          },
          {
            "title": "group lighting",
            "description": "Illuminates the working area in front of the groups."
          }
        ]
      },
      "kz": {
        "name": "Eagle Tempo Neo 2 Group",
        "description": "Көп бойлерлі жылыту жүйесі және цифрлық басқаруы бар екі топты Eagle Tempo Neo. Кофе мен сүтті сусындарға арналған.",
        "category": "Кәсіби кофемашина",
        "status_label": "Тапсырыспен",
        "seo_title": "Eagle Tempo Neo 2 Group | Sketo",
        "seo_description": "Көп бойлерлі жылыту жүйесі және цифрлық басқаруы бар екі топты Eagle Tempo Neo. Кофе мен сүтті сусындарға арналған.",
        "details": [
          {
            "label": "Бренд",
            "value": "Victoria Arduino"
          },
          {
            "label": "Сериясы",
            "value": "Eagle Tempo Neo"
          },
          {
            "label": "Топ саны",
            "value": "2"
          },
          {
            "label": "Мақсаты",
            "value": "Эспрессо"
          }
        ],
        "specifications": [
          {
            "label": "Биіктігі",
            "value": "416 мм"
          },
          {
            "label": "Ені",
            "value": "825 мм"
          },
          {
            "label": "Тереңдігі",
            "value": "650 мм"
          },
          {
            "label": "Салмағы",
            "value": "62 кг"
          },
          {
            "label": "Жылыту жүйесі",
            "value": "NEO"
          }
        ],
        "features": [
          {
            "title": "NEO",
            "description": "Демдеуге қажетті су көлемін қыздырады."
          },
          {
            "title": "сенсорлық басқару",
            "description": "Экран рецепт таңдауды және баптауды жеңілдетеді."
          },
          {
            "title": "автоматты шаю",
            "description": "Автоматты шаю жұмыс барысын жеңілдетеді."
          },
          {
            "title": "топтарды жарықтандыру",
            "description": "Топтардың алдындағы жұмыс аймағын жарықтандырады."
          }
        ]
      }
    },
    "sources": [
      "https://victoriaarduino.com/en/products-machines/eagle-tempo/"
    ],
    "document": "Уточнения пользователя от 07.10.2026",
    "note": "Конфликт: пользователь сообщил 3200 Вт / 11 л; текущая официальная таблица Neo 2GR показывает 6000/7400 Вт / 8 л, а Digit 11–17 л. Мощность и ёмкость исключены до получения шильдика/паспорта конкретного исполнения."
  },
  {
    "slug": "victoria-arduino-black-eagle-maverick-gravitech",
    "name": "Black Eagle Maverick Gravitech",
    "brand": "victoria-arduino",
    "equipment_type": "espresso-machine",
    "aliases": [
      "blackeaglemaverickgravitech",
      "victoriaarduinoblackeaglemaverick",
      "victoriaarduinoblackeaglemaverickgravitech",
      "victoriaarduinomaverick"
    ],
    "translations": {
      "ru": {
        "name": "Black Eagle Maverick Gravitech",
        "description": "Black Eagle Maverick с гравиметрическим дозированием и контролем температуры T3 Genius. Для точной работы с рецептами эспрессо.",
        "category": "Коммерческая кофемашина",
        "status_label": "Под заказ",
        "seo_title": "Black Eagle Maverick Gravitech | Sketo",
        "seo_description": "Black Eagle Maverick с гравиметрическим дозированием и контролем температуры T3 Genius. Для точной работы с рецептами эспрессо.",
        "details": [
          {
            "label": "Бренд",
            "value": "Victoria Arduino"
          },
          {
            "label": "Серия",
            "value": "Black Eagle Maverick"
          },
          {
            "label": "Варианты исполнения",
            "value": "2 или 3 группы"
          },
          {
            "label": "Управление",
            "value": "Дозирование по весу"
          }
        ],
        "specifications": [
          {
            "label": "Высота",
            "value": "426 мм"
          },
          {
            "label": "Ширина",
            "value": "2 группы: 806 мм; 3 группы: 1056 мм"
          },
          {
            "label": "Глубина",
            "value": "682 мм"
          },
          {
            "label": "Вес",
            "value": "2 группы: 90 кг; 3 группы: 115 кг"
          },
          {
            "label": "Мощность",
            "value": "2 группы: 6800 Вт; 3 группы: 8600 Вт"
          }
        ],
        "features": [
          {
            "title": "Gravitech",
            "description": "Вес напитка отображается на дисплее группы."
          },
          {
            "title": "T3 Genius",
            "description": "Точная настройка температуры заваривания."
          },
          {
            "title": "TERS",
            "description": "Возвращает тепло отработанной воды для предварительного нагрева."
          },
          {
            "title": "PureBrew",
            "description": "Дополнительный способ приготовления кофе и настоев."
          }
        ]
      },
      "en": {
        "name": "Black Eagle Maverick Gravitech",
        "description": "Black Eagle Maverick with gravimetric dosing and T3 Genius temperature control for precise espresso recipes.",
        "category": "Commercial espresso machine",
        "status_label": "On request",
        "seo_title": "Black Eagle Maverick Gravitech | Sketo",
        "seo_description": "Black Eagle Maverick with gravimetric dosing and T3 Genius temperature control for precise espresso recipes.",
        "details": [
          {
            "label": "Brand",
            "value": "Victoria Arduino"
          },
          {
            "label": "Series",
            "value": "Black Eagle Maverick"
          },
          {
            "label": "Available configurations",
            "value": "2 or 3 groups"
          },
          {
            "label": "Control",
            "value": "Weight-based dosing"
          }
        ],
        "specifications": [
          {
            "label": "Height",
            "value": "426 mm"
          },
          {
            "label": "Width",
            "value": "2 groups: 806 mm; 3 groups: 1056 mm"
          },
          {
            "label": "Depth",
            "value": "682 mm"
          },
          {
            "label": "Weight",
            "value": "2 groups: 90 kg; 3 groups: 115 kg"
          },
          {
            "label": "Power",
            "value": "2 groups: 6800 W; 3 groups: 8600 W"
          }
        ],
        "features": [
          {
            "title": "Gravitech",
            "description": "The group display shows beverage weight."
          },
          {
            "title": "T3 Genius",
            "description": "Precise brewing temperature settings."
          },
          {
            "title": "TERS",
            "description": "Recovers heat from waste water for preheating."
          },
          {
            "title": "PureBrew",
            "description": "An additional brewing method for coffee and infusions."
          }
        ]
      },
      "kz": {
        "name": "Black Eagle Maverick Gravitech",
        "description": "Гравиметриялық мөлшерлеуі және T3 Genius температура бақылауы бар Black Eagle Maverick. Дәл эспрессо рецепттеріне арналған.",
        "category": "Кәсіби кофемашина",
        "status_label": "Тапсырыспен",
        "seo_title": "Black Eagle Maverick Gravitech | Sketo",
        "seo_description": "Гравиметриялық мөлшерлеуі және T3 Genius температура бақылауы бар Black Eagle Maverick. Дәл эспрессо рецепттеріне арналған.",
        "details": [
          {
            "label": "Бренд",
            "value": "Victoria Arduino"
          },
          {
            "label": "Сериясы",
            "value": "Black Eagle Maverick"
          },
          {
            "label": "Орындалу нұсқалары",
            "value": "2 немесе 3 топ"
          },
          {
            "label": "Басқару",
            "value": "Салмақ бойынша мөлшерлеу"
          }
        ],
        "specifications": [
          {
            "label": "Биіктігі",
            "value": "426 мм"
          },
          {
            "label": "Ені",
            "value": "2 топ: 806 мм; 3 топ: 1056 мм"
          },
          {
            "label": "Тереңдігі",
            "value": "682 мм"
          },
          {
            "label": "Салмағы",
            "value": "2 топ: 90 кг; 3 топ: 115 кг"
          },
          {
            "label": "Қуаты",
            "value": "2 топ: 6800 Вт; 3 топ: 8600 Вт"
          }
        ],
        "features": [
          {
            "title": "Gravitech",
            "description": "Топ дисплейі сусын салмағын көрсетеді."
          },
          {
            "title": "T3 Genius",
            "description": "Демдеу температурасын дәл баптау."
          },
          {
            "title": "TERS",
            "description": "Алдын ала қыздыру үшін пайдаланылған судың жылуын қайта қолданады."
          },
          {
            "title": "PureBrew",
            "description": "Кофе мен тұнбаларды дайындаудың қосымша тәсілі."
          }
        ]
      }
    },
    "sources": [
      "https://victoriaarduino.com/en/products-machines/black-eagle-maverick/"
    ],
    "document": "Уточнения пользователя от 07.10.2026",
    "note": "Gravitech подтверждено пользователем; группы не выбраны. Текущая страница: 426×682 мм высота/глубина, 6800/8600 Вт. Более ранние 433×745 мм и 6900/8700 Вт не смешивались с текущей версией. Не Maverick Core."
  },
  {
    "slug": "modbar-espresso-av-1-group",
    "name": "Modbar Espresso AV 1 Group",
    "brand": "modbar",
    "equipment_type": "espresso-machine",
    "aliases": [
      "modbarespressoav",
      "modbarespressoav1group",
      "modbarmodbarespressoav1group"
    ],
    "translations": {
      "ru": {
        "name": "Modbar Espresso AV 1 Group",
        "description": "Одногрупповая эспрессо-система с подстольным модулем и объёмным дозированием. Открытая компоновка оставляет больше пространства над стойкой.",
        "category": "Коммерческая кофемашина",
        "status_label": "Под заказ",
        "seo_title": "Modbar Espresso AV 1 Group | Sketo",
        "seo_description": "Одногрупповая эспрессо-система с подстольным модулем и объёмным дозированием. Открытая компоновка оставляет больше пространства над стойкой.",
        "details": [
          {
            "label": "Бренд",
            "value": "Modbar"
          },
          {
            "label": "Серия",
            "value": "Espresso AV"
          },
          {
            "label": "Группы",
            "value": "1"
          },
          {
            "label": "Управление",
            "value": "Автоматическое объёмное"
          }
        ],
        "specifications": [
          {
            "label": "Модуль: Ш × Г × В",
            "value": "430 × 380 × 220 мм"
          },
          {
            "label": "Кран: Ш × Г × В",
            "value": "140 × 320 × 360 мм"
          },
          {
            "label": "Вес модуля",
            "value": "16.5 кг"
          },
          {
            "label": "Вес крана",
            "value": "10.5 кг"
          },
          {
            "label": "Бойлер",
            "value": "1.4 л"
          },
          {
            "label": "Мощность",
            "value": "1545 Вт (208–240 В)"
          }
        ],
        "features": [
          {
            "title": "объёмное дозирование",
            "description": "Пролив останавливается после заданного объёма."
          },
          {
            "title": "PID",
            "description": "Электронная регулировка температуры заваривания."
          },
          {
            "title": "программируемый рычаг",
            "description": "Четыре положения для управления приготовлением."
          },
          {
            "title": "таймер пролива",
            "description": "Дисплей показывает время приготовления."
          }
        ]
      },
      "en": {
        "name": "Modbar Espresso AV 1 Group",
        "description": "A single-group espresso system with an under-counter module and volumetric dosing for an open counter layout.",
        "category": "Commercial espresso machine",
        "status_label": "On request",
        "seo_title": "Modbar Espresso AV 1 Group | Sketo",
        "seo_description": "A single-group espresso system with an under-counter module and volumetric dosing for an open counter layout.",
        "details": [
          {
            "label": "Brand",
            "value": "Modbar"
          },
          {
            "label": "Series",
            "value": "Espresso AV"
          },
          {
            "label": "Groups",
            "value": "1"
          },
          {
            "label": "Control",
            "value": "Automatic volumetric"
          }
        ],
        "specifications": [
          {
            "label": "Module: W × D × H",
            "value": "430 × 380 × 220 mm"
          },
          {
            "label": "Tap: W × D × H",
            "value": "140 × 320 × 360 mm"
          },
          {
            "label": "Module weight",
            "value": "16.5 kg"
          },
          {
            "label": "Tap weight",
            "value": "10.5 kg"
          },
          {
            "label": "Boiler",
            "value": "1.4 L"
          },
          {
            "label": "Power",
            "value": "1545 W (208–240 V)"
          }
        ],
        "features": [
          {
            "title": "volumetric dosing",
            "description": "Extraction stops at the programmed volume."
          },
          {
            "title": "PID",
            "description": "Electronic brewing temperature control."
          },
          {
            "title": "programmable lever",
            "description": "Four positions control brewing."
          },
          {
            "title": "shot timer",
            "description": "The display shows brewing time."
          }
        ]
      },
      "kz": {
        "name": "Modbar Espresso AV 1 Group",
        "description": "Үстел асты модулі және көлемдік мөлшерлеуі бар бір топты эспрессо жүйесі. Ашық құрылымы үстел үстіндегі орынды босатады.",
        "category": "Кәсіби кофемашина",
        "status_label": "Тапсырыспен",
        "seo_title": "Modbar Espresso AV 1 Group | Sketo",
        "seo_description": "Үстел асты модулі және көлемдік мөлшерлеуі бар бір топты эспрессо жүйесі. Ашық құрылымы үстел үстіндегі орынды босатады.",
        "details": [
          {
            "label": "Бренд",
            "value": "Modbar"
          },
          {
            "label": "Сериясы",
            "value": "Espresso AV"
          },
          {
            "label": "Топ саны",
            "value": "1"
          },
          {
            "label": "Басқару",
            "value": "Автоматты көлемдік"
          }
        ],
        "specifications": [
          {
            "label": "Модуль: Е × Т × Б",
            "value": "430 × 380 × 220 мм"
          },
          {
            "label": "Кран: Е × Т × Б",
            "value": "140 × 320 × 360 мм"
          },
          {
            "label": "Модуль салмағы",
            "value": "16.5 кг"
          },
          {
            "label": "Кран салмағы",
            "value": "10.5 кг"
          },
          {
            "label": "Бойлер",
            "value": "1.4 л"
          },
          {
            "label": "Қуаты",
            "value": "1545 Вт (208–240 В)"
          }
        ],
        "features": [
          {
            "title": "көлемдік мөлшерлеу",
            "description": "Белгіленген көлемге жеткенде су беру тоқтайды."
          },
          {
            "title": "PID",
            "description": "Демдеу температурасын электронды реттеу."
          },
          {
            "title": "бағдарламаланатын тұтқа",
            "description": "Төрт қалып дайындауды басқарады."
          },
          {
            "title": "су беру таймері",
            "description": "Дисплей дайындау уақытын көрсетеді."
          }
        ]
      }
    },
    "sources": [
      "https://modbar.com/wp-content/uploads/free/ESPRESSO-AV-SYSTEM/Brochure-Modbar-Espresso-AV.pdf"
    ],
    "document": "Уточнения пользователя от 07.10.2026",
    "note": "MOD 1 GR, не двухгрупповой модуль с одним подключённым краном. Размеры/масса модуля и крана разделены. Состав поставки и ABR не заявлены."
  },
  {
    "slug": "modbar-single-drip-tray",
    "name": "Modbar Single Drip Tray",
    "brand": "modbar",
    "equipment_type": "accessory",
    "aliases": [
      "modbarmodbarsingledriptray",
      "modbarsingledriptray"
    ],
    "translations": {
      "ru": {
        "name": "Modbar Single Drip Tray",
        "description": "Одинарный поддон для сбора капель в рабочей зоне Modbar. Дополняет открытую компоновку кофейной стойки.",
        "category": "Аксессуар",
        "status_label": "Под заказ",
        "seo_title": "Modbar Single Drip Tray | Sketo",
        "seo_description": "Одинарный поддон для сбора капель в рабочей зоне Modbar. Дополняет открытую компоновку кофейной стойки.",
        "details": [
          {
            "label": "Бренд",
            "value": "Modbar"
          },
          {
            "label": "Серия",
            "value": "Single Drip Tray"
          },
          {
            "label": "Формат",
            "value": "Одинарный поддон"
          },
          {
            "label": "Назначение",
            "value": "Сбор капель"
          }
        ],
        "specifications": [
          {
            "label": "Совместимость",
            "value": "Modbar"
          },
          {
            "label": "Формат",
            "value": "Поддон для капель"
          }
        ],
        "features": [
          {
            "title": "рабочая зона Modbar",
            "description": "Поддон собирает капли под зоной приготовления."
          },
          {
            "title": "единый дизайн",
            "description": "Сочетается с открытой компоновкой Modbar."
          }
        ]
      },
      "en": {
        "name": "Modbar Single Drip Tray",
        "description": "A single drip tray for the Modbar work area, complementing an open coffee counter.",
        "category": "Accessory",
        "status_label": "On request",
        "seo_title": "Modbar Single Drip Tray | Sketo",
        "seo_description": "A single drip tray for the Modbar work area, complementing an open coffee counter.",
        "details": [
          {
            "label": "Brand",
            "value": "Modbar"
          },
          {
            "label": "Series",
            "value": "Single Drip Tray"
          },
          {
            "label": "Format",
            "value": "Single drip tray"
          },
          {
            "label": "Application",
            "value": "Drip collection"
          }
        ],
        "specifications": [
          {
            "label": "Compatibility",
            "value": "Modbar"
          },
          {
            "label": "Format",
            "value": "Drip tray"
          }
        ],
        "features": [
          {
            "title": "Modbar work area",
            "description": "Collects drips beneath the brewing area."
          },
          {
            "title": "coordinated design",
            "description": "Complements the open Modbar layout."
          }
        ]
      },
      "kz": {
        "name": "Modbar Single Drip Tray",
        "description": "Modbar жұмыс аймағындағы тамшыларды жинайтын бірлік науа. Ашық кофе үстелін толықтырады.",
        "category": "Керек-жарақ",
        "status_label": "Тапсырыспен",
        "seo_title": "Modbar Single Drip Tray | Sketo",
        "seo_description": "Modbar жұмыс аймағындағы тамшыларды жинайтын бірлік науа. Ашық кофе үстелін толықтырады.",
        "details": [
          {
            "label": "Бренд",
            "value": "Modbar"
          },
          {
            "label": "Сериясы",
            "value": "Single Drip Tray"
          },
          {
            "label": "Пішімі",
            "value": "Бірлік науа"
          },
          {
            "label": "Мақсаты",
            "value": "Тамшыларды жинау"
          }
        ],
        "specifications": [
          {
            "label": "Үйлесімділік",
            "value": "Modbar"
          },
          {
            "label": "Пішімі",
            "value": "Тамшы науасы"
          }
        ],
        "features": [
          {
            "title": "Modbar жұмыс аймағы",
            "description": "Дайындау аймағының астындағы тамшыларды жинайды."
          },
          {
            "title": "үйлесімді дизайн",
            "description": "Modbar ашық құрылымымен үйлеседі."
          }
        ]
      }
    },
    "sources": [
      "https://modbar.com/complementary-products/"
    ],
    "document": "Уточнения пользователя от 07.10.2026",
    "note": "433×1056×745 не подтверждены для поддона и исключены. Точный артикул и чертёж нужны для габаритов; не назначены размеры поддона с ринзером, ABR, материал и комплектность."
  }
]
$equipment$::jsonb) WITH ORDINALITY;

CREATE TEMP TABLE sketo_equipment_result (
  requested_slug text PRIMARY KEY,
  product_id uuid NOT NULL,
  created boolean NOT NULL
) ON COMMIT DROP;

DO $import$
DECLARE
  item jsonb;
  tr jsonb;
  entry jsonb;
  language text;
  ordinal integer;
  target uuid;
  matched uuid[];
  existing_record public.products%ROWTYPE;
  next_order integer;
  placeholder text := 'data:image/svg+xml,%3Csvg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 600 600"%3E%3Crect width="600" height="600" fill="%23f2f0eb"/%3E%3Cpath d="M300 220v160M220 300h160" stroke="%23ce1616" stroke-width="10"/%3E%3C/svg%3E';
BEGIN
  IF (SELECT count(*) FROM sketo_equipment_source) <> 8 THEN
    RAISE EXCEPTION 'Unexpected source product count.';
  END IF;
  SELECT COALESCE(max(sort_order), -1) + 1 INTO next_order FROM public.products WHERE type='equipment';
  FOR item IN SELECT data FROM sketo_equipment_source ORDER BY position LOOP
    SELECT array_agg(DISTINCT p.id) INTO matched
    FROM public.products p
    LEFT JOIN public.product_translations translations ON translations.product_id=p.id
    WHERE p.slug=item->>'slug'
       OR (p.type='equipment' AND (
         item->'aliases' ? regexp_replace(translate(lower(COALESCE(p.name,'')), 'ö', 'o'), '[^a-z0-9]', '', 'g')
         OR item->'aliases' ? regexp_replace(translate(lower(p.slug), 'ö', 'o'), '[^a-z0-9]', '', 'g')
         OR item->'aliases' ? regexp_replace(translate(lower(COALESCE(translations.name,'')), 'ö', 'o'), '[^a-z0-9]', '', 'g')
       ));
    IF COALESCE(cardinality(matched),0)>1 THEN
      RAISE EXCEPTION 'Several existing products match %. Resolve duplicates first: %', item->>'slug', matched;
    END IF;
    IF COALESCE(cardinality(matched),0)=1 THEN
      SELECT * INTO existing_record FROM public.products WHERE id=matched[1];
      IF existing_record.type::text <> 'equipment'
         OR existing_record.brand::text IS DISTINCT FROM item->>'brand'
         OR existing_record.equipment_type::text IS DISTINCT FROM item->>'equipment_type' THEN
        RAISE EXCEPTION 'Existing product % conflicts with brand/type for %; inspect manually.', existing_record.slug, item->>'slug';
      END IF;
      INSERT INTO sketo_equipment_result VALUES (item->>'slug', matched[1], false);
      CONTINUE; -- Preserve ALL text, images, prices, state and ordering of existing cards.
    END IF;

    INSERT INTO public.products
      (slug,name,sku,type,status,editorial_state,image_url,brand,equipment_type,
       price_display,price_amount,price_currency,filters,sort_order,is_featured,is_published,published_at)
    VALUES
      (item->>'slug',item->>'name',upper(item->>'slug'),'equipment','preorder','draft',placeholder,
       (item->>'brand')::public.equipment_brand,(item->>'equipment_type')::public.equipment_type,
       NULL,NULL,'KZT',ARRAY[]::text[],next_order,false,false,NULL)
    RETURNING id INTO target;
    next_order := next_order+1;
    INSERT INTO sketo_equipment_result VALUES (item->>'slug',target,true);
    INSERT INTO public.product_images (product_id,url,sort_order,is_primary) VALUES (target,placeholder,0,true);

    FOREACH language IN ARRAY ARRAY['ru','en','kz'] LOOP
      tr := item->'translations'->language;
      IF tr IS NULL OR COALESCE(tr->>'description','')='' OR COALESCE(tr->>'name','')='' THEN
        RAISE EXCEPTION 'Missing translation % for %.',language,item->>'slug';
      END IF;
      INSERT INTO public.product_translations
        (product_id,locale,name,description,category,status_label,seo_title,seo_description)
      VALUES
        (target,language::public.locale,tr->>'name',tr->>'description',tr->>'category',tr->>'status_label',tr->>'seo_title',tr->>'seo_description');
      ordinal := 0;
      FOR entry IN SELECT value FROM jsonb_array_elements(tr->'details') LOOP
        INSERT INTO public.product_details (product_id,locale,kind,label,value,sort_order)
        VALUES (target,language::public.locale,'detail',entry->>'label',entry->>'value',ordinal);
        ordinal := ordinal+1;
      END LOOP;
      ordinal := 0;
      FOR entry IN SELECT value FROM jsonb_array_elements(tr->'specifications') LOOP
        INSERT INTO public.product_details (product_id,locale,kind,label,value,sort_order)
        VALUES (target,language::public.locale,'specification',entry->>'label',entry->>'value',ordinal);
        ordinal := ordinal+1;
      END LOOP;
      ordinal := 0;
      FOR entry IN SELECT value FROM jsonb_array_elements(tr->'features') LOOP
        INSERT INTO public.product_features (product_id,locale,title,description,sort_order)
        VALUES (target,language::public.locale,entry->>'title',entry->>'description',ordinal);
        ordinal := ordinal+1;
      END LOOP;
    END LOOP;
    INSERT INTO public.audit_logs (entity_type,entity_id,action,summary,diff)
    VALUES ('product',target,'create','Импортирован черновик оборудования: ' || (item->>'name'),
      jsonb_build_object('source','20261007_equipment_followup.sql','locales',jsonb_build_array('ru','en','kz'),
        'sources',item->'sources','editorial_state','draft','status_is_provisional',true));
  END LOOP;
END;
$import$;

DO $validate$
BEGIN
  IF EXISTS (
    SELECT 1 FROM sketo_equipment_result r
    JOIN sketo_equipment_source s ON s.data->>'slug'=r.requested_slug
    CROSS JOIN (VALUES ('ru'),('en'),('kz')) languages(locale)
    WHERE r.created AND (
      (SELECT count(*) FROM public.product_translations t WHERE t.product_id=r.product_id AND t.locale::text=languages.locale)<>1
      OR (SELECT count(*) FROM public.product_details d WHERE d.product_id=r.product_id AND d.locale::text=languages.locale AND d.kind='detail')<>4
      OR (SELECT count(*) FROM public.product_details d WHERE d.product_id=r.product_id AND d.locale::text=languages.locale AND d.kind='specification')<>jsonb_array_length(s.data->'translations'->languages.locale->'specifications')
      OR (SELECT count(*) FROM public.product_features f WHERE f.product_id=r.product_id AND f.locale::text=languages.locale)<>jsonb_array_length(s.data->'translations'->languages.locale->'features')
    )
  ) THEN
    RAISE EXCEPTION 'Import validation failed. Transaction will be rolled back.';
  END IF;
END;
$validate$;

SELECT r.requested_slug, p.slug AS actual_slug,
       CASE WHEN r.created THEN 'created_draft' ELSE 'skipped_existing' END AS result,
       p.editorial_state, p.is_published
FROM sketo_equipment_result r JOIN public.products p ON p.id=r.product_id
ORDER BY r.requested_slug;
COMMIT;
