-- Sketo equipment import, 2026-10-07. Generated by build_equipment_import.py.
-- First commit migrations/20261007010000_equipment_catalog_types.sql separately.
-- 22 candidate products, RU/EN/KZ. Existing matches are skipped IN FULL.
-- Draft/unpublished, no prices; preorder is a provisional editorial default.
-- Sources and exclusions: 20261007_equipment_sources.md / 20261007_equipment_README.md.
-- Execute generated 20261007_equipment_catalog.sql in full, outside an existing transaction.
-- Do not execute equipment_import.template.sql.

BEGIN;
SET LOCAL lock_timeout = '10s';
SET LOCAL search_path = public, pg_temp;
SELECT pg_advisory_xact_lock(hashtext('sketo:equipment-import:20261007'));

DO $preflight$
BEGIN
  IF to_regclass('public.products') IS NULL OR to_regclass('public.audit_logs') IS NULL THEN
    RAISE EXCEPTION 'Apply catalog and editor foundation migrations before this import.';
  END IF;
  IF EXISTS (
    SELECT 1 FROM (VALUES
      ('locale','kz'), ('equipment_brand','nuova-simonelli'),
      ('equipment_brand','eureka'), ('equipment_brand','modbar'),
      ('equipment_brand','puqpress'), ('equipment_type','tamper'),
      ('equipment_type','steam-module')
    ) AS required(type_name,label)
    WHERE NOT EXISTS (
      SELECT 1 FROM pg_enum e JOIN pg_type t ON t.oid=e.enumtypid
      JOIN pg_namespace n ON n.oid=t.typnamespace
      WHERE n.nspname='public' AND t.typname=required.type_name AND e.enumlabel=required.label
    )
  ) THEN
    RAISE EXCEPTION 'Apply and COMMIT 20261007010000_equipment_catalog_types.sql and the KZ locale migration first.';
  END IF;
END;
$preflight$;

CREATE TEMP TABLE sketo_equipment_source ON COMMIT DROP AS
SELECT value AS data, ordinality AS position
FROM jsonb_array_elements($equipment$
__EQUIPMENT_JSON__
$equipment$::jsonb) WITH ORDINALITY;

CREATE TEMP TABLE sketo_equipment_result (
  requested_slug text PRIMARY KEY,
  product_id uuid NOT NULL,
  created boolean NOT NULL
) ON COMMIT DROP;

DO $import$
DECLARE
  item jsonb;
  tr jsonb;
  entry jsonb;
  language text;
  ordinal integer;
  target uuid;
  matched uuid[];
  existing_record public.products%ROWTYPE;
  next_order integer;
  placeholder text := 'data:image/svg+xml,%3Csvg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 600 600"%3E%3Crect width="600" height="600" fill="%23f2f0eb"/%3E%3Cpath d="M300 220v160M220 300h160" stroke="%23ce1616" stroke-width="10"/%3E%3C/svg%3E';
BEGIN
  IF (SELECT count(*) FROM sketo_equipment_source) <> 22 THEN
    RAISE EXCEPTION 'Unexpected source product count.';
  END IF;
  SELECT COALESCE(max(sort_order), -1) + 1 INTO next_order FROM public.products WHERE type='equipment';
  FOR item IN SELECT data FROM sketo_equipment_source ORDER BY position LOOP
    SELECT array_agg(DISTINCT p.id) INTO matched
    FROM public.products p
    LEFT JOIN public.product_translations translations ON translations.product_id=p.id
    WHERE p.slug=item->>'slug'
       OR (p.type='equipment' AND (
         item->'aliases' ? regexp_replace(translate(lower(COALESCE(p.name,'')), 'ö', 'o'), '[^a-z0-9]', '', 'g')
         OR item->'aliases' ? regexp_replace(translate(lower(p.slug), 'ö', 'o'), '[^a-z0-9]', '', 'g')
         OR item->'aliases' ? regexp_replace(translate(lower(COALESCE(translations.name,'')), 'ö', 'o'), '[^a-z0-9]', '', 'g')
       ));
    IF COALESCE(cardinality(matched),0)>1 THEN
      RAISE EXCEPTION 'Several existing products match %. Resolve duplicates first: %', item->>'slug', matched;
    END IF;
    IF COALESCE(cardinality(matched),0)=1 THEN
      SELECT * INTO existing_record FROM public.products WHERE id=matched[1];
      IF existing_record.type::text <> 'equipment'
         OR existing_record.brand::text IS DISTINCT FROM item->>'brand'
         OR existing_record.equipment_type::text IS DISTINCT FROM item->>'equipment_type' THEN
        RAISE EXCEPTION 'Existing product % conflicts with brand/type for %; inspect manually.', existing_record.slug, item->>'slug';
      END IF;
      INSERT INTO sketo_equipment_result VALUES (item->>'slug', matched[1], false);
      CONTINUE; -- Preserve ALL text, images, prices, state and ordering of existing cards.
    END IF;

    INSERT INTO public.products
      (slug,name,sku,type,status,editorial_state,image_url,brand,equipment_type,
       price_display,price_amount,price_currency,filters,sort_order,is_featured,is_published,published_at)
    VALUES
      (item->>'slug',item->>'name',upper(item->>'slug'),'equipment','preorder','draft',placeholder,
       (item->>'brand')::public.equipment_brand,(item->>'equipment_type')::public.equipment_type,
       NULL,NULL,'KZT',ARRAY[]::text[],next_order,false,false,NULL)
    RETURNING id INTO target;
    next_order := next_order+1;
    INSERT INTO sketo_equipment_result VALUES (item->>'slug',target,true);
    INSERT INTO public.product_images (product_id,url,sort_order,is_primary) VALUES (target,placeholder,0,true);

    FOREACH language IN ARRAY ARRAY['ru','en','kz'] LOOP
      tr := item->'translations'->language;
      IF tr IS NULL OR COALESCE(tr->>'description','')='' OR COALESCE(tr->>'name','')='' THEN
        RAISE EXCEPTION 'Missing translation % for %.',language,item->>'slug';
      END IF;
      INSERT INTO public.product_translations
        (product_id,locale,name,description,category,status_label,seo_title,seo_description)
      VALUES
        (target,language::public.locale,tr->>'name',tr->>'description',tr->>'category',tr->>'status_label',tr->>'seo_title',tr->>'seo_description');
      ordinal := 0;
      FOR entry IN SELECT value FROM jsonb_array_elements(tr->'details') LOOP
        INSERT INTO public.product_details (product_id,locale,kind,label,value,sort_order)
        VALUES (target,language::public.locale,'detail',entry->>'label',entry->>'value',ordinal);
        ordinal := ordinal+1;
      END LOOP;
      ordinal := 0;
      FOR entry IN SELECT value FROM jsonb_array_elements(tr->'specifications') LOOP
        INSERT INTO public.product_details (product_id,locale,kind,label,value,sort_order)
        VALUES (target,language::public.locale,'specification',entry->>'label',entry->>'value',ordinal);
        ordinal := ordinal+1;
      END LOOP;
      ordinal := 0;
      FOR entry IN SELECT value FROM jsonb_array_elements(tr->'features') LOOP
        INSERT INTO public.product_features (product_id,locale,title,description,sort_order)
        VALUES (target,language::public.locale,entry->>'title',entry->>'description',ordinal);
        ordinal := ordinal+1;
      END LOOP;
    END LOOP;
    INSERT INTO public.audit_logs (entity_type,entity_id,action,summary,diff)
    VALUES ('product',target,'create','Импортирован черновик оборудования: ' || (item->>'name'),
      jsonb_build_object('source','20261007_equipment_catalog.sql','locales',jsonb_build_array('ru','en','kz'),
        'sources',item->'sources','editorial_state','draft','status_is_provisional',true));
  END LOOP;
END;
$import$;

DO $validate$
BEGIN
  IF EXISTS (
    SELECT 1 FROM sketo_equipment_result r
    JOIN sketo_equipment_source s ON s.data->>'slug'=r.requested_slug
    CROSS JOIN (VALUES ('ru'),('en'),('kz')) languages(locale)
    WHERE r.created AND (
      (SELECT count(*) FROM public.product_translations t WHERE t.product_id=r.product_id AND t.locale::text=languages.locale)<>1
      OR (SELECT count(*) FROM public.product_details d WHERE d.product_id=r.product_id AND d.locale::text=languages.locale AND d.kind='detail')<>4
      OR (SELECT count(*) FROM public.product_details d WHERE d.product_id=r.product_id AND d.locale::text=languages.locale AND d.kind='specification')<>jsonb_array_length(s.data->'translations'->languages.locale->'specifications')
      OR (SELECT count(*) FROM public.product_features f WHERE f.product_id=r.product_id AND f.locale::text=languages.locale)<>jsonb_array_length(s.data->'translations'->languages.locale->'features')
    )
  ) THEN
    RAISE EXCEPTION 'Import validation failed. Transaction will be rolled back.';
  END IF;
END;
$validate$;

SELECT r.requested_slug, p.slug AS actual_slug,
       CASE WHEN r.created THEN 'created_draft' ELSE 'skipped_existing' END AS result,
       p.editorial_state, p.is_published
FROM sketo_equipment_result r JOIN public.products p ON p.id=r.product_id
ORDER BY r.requested_slug;
COMMIT;
