"use client";

import usePersistentLanguage from "./usePersistentLanguage";

// Legacy editorial headings shared by the Russian and English layouts.
const kazakh: Record<string, string> = {
  "concept": "тұжырымдама",
  "equipment": "жабдық",
  "bar": "бар",
  "menu": "мәзір",
  "training": "оқыту",
  "launch": "іске қосу",
  "support": "қолдау",
  "Загружаем…": "Жүктелуде…",
  "Повторить загрузку": "Қайта жүктеу",
  "academy as system": "академия — біртұтас жүйе",
  "academy": "академия",
  "sketo academy program": "sketo академиясының бағдарламасы",
  "faq": "жиі қойылатын сұрақтар",
  "next step": "келесі қадам",
  "service map": "қызметтер картасы",
  "From concept": "Идеядан",
  "to daily": "күнделікті",
  "operation": "жұмысқа дейін",
  "b2b / service blueprint": "b2b / қызмет көрсету жоспары",
  "for Business": "бизнес үшін",
  "full coffee project cycle": "кофе жобасының толық циклі",
  "equipment / bar / menu / training / support": "жабдық / бар / мәзір / оқу / қолдау",
  "practical systems for real operations": "күнделікті жұмысқа арналған практикалық жүйелер",
  "workflow / how it works": "жұмыс барысы / қалай іске асады",
  "How": "Жұмыс",
  "work moves": "қалай жүреді",
  "About Sketo": "Sketo туралы",
  "Не удалось загрузить каталог": "Каталогты жүктеу мүмкін болмады",
  "Данные временно недоступны. Попробуйте загрузить страницу ещё раз.": "Деректер уақытша қолжетімсіз. Бетті қайта жүктеп көріңіз.",
  "На главную": "Басты бетке",
  "coffee and all about.": "кофе және ол туралы бәрі.",
  "Why Sketo": "Неліктен Sketo",
  "We build coffee around clarity, character and a quiet confidence in every detail.": "Біз кофе әлемін айқындық, өзіндік мінез және әр бөлшекке деген байыпты сенім негізінде құрамыз.",
  "matcha ritual / slow green": "матча рәсімі / жасыл тыныштық",
  "Фокус": "Зейін",
  "и красивая пауза": "және әсем үзіліс",
  "summer / 2026": "жаз / 2026",
  "Сезонное": "Маусымдық",
  "меню": "мәзір",
  "background": "тәжірибе",
  "focus": "негізгі бағыт",
  "A closer look at how Sketo thinks about sourcing, roast logic, seasonality and quality.": "Sketo-ның жеткізу, қуыру қағидалары, маусымдылық және сапа туралы көзқарасына жақынырақ үңіліңіз.",
  "The menu is only the visible layer. Behind it sits a quieter system of decisions that shapes how coffee tastes, moves, and stays consistent day after day.": "Мәзір — тек көрінетін бөлік. Оның артында кофенің дәмін, жолын және күн сайынғы тұрақтылығын қалыптастыратын шешімдер жүйесі бар.",
  "Open the full Why Sketo page for the brand logic, internal structure, and the principles that hold the whole cup together.": "Брендтің тәсілі, ішкі құрылымы және кеседегі дәмді біріктіретін қағидалар туралы білу үшін «Неліктен Sketo» бетін ашыңыз.",
  "Open why sketo": "Неліктен Sketo бетін ашу",
  "View catalogue": "Каталогты қарау",
  "origin first": "алдымен шығу тегі",
  "direct sourcing": "тікелей жеткізу",
  "Traceability": "Шығу тегінің ашықтығы",
  "Roast precision": "Қуыру дәлдігі",
  "Seasonal clarity": "Маусымдық айқындық",
  "Sketo select": "Sketo таңдауы",
  "Origin, process and roast profile aligned for a cleaner reading in the cup.": "Кеседегі дәм айқынырақ болуы үшін шығу тегі, өңдеу және қуыру профилі үйлестірілген.",
  "Direct sourcing": "Тікелей жеткізу",
  "Sketo works with direct sourcing, clear origin and coffees chosen for character over noise.": "Sketo тікелей жеткізіліммен, шығу тегі анық және өзіндік сипаты үшін таңдалған кофемен жұмыс істейді.",
  "We select coffees where the producer, process and regional identity remain readable in the cup. That gives us a cleaner foundation for roasting, storytelling and long-term quality.": "Біз өндірушісі, өңдеу тәсілі және аймақтық сипаты кеседен сезілетін кофені таңдаймыз. Бұл қуыруға, кофе тарихын жеткізуге және ұзақ мерзімді сапаға берік негіз береді.",
  "This approach keeps the coffee honest: fewer distractions, more clarity, and a profile that feels intentional from first aroma to finish.": "Бұл тәсіл кофенің табиғи сипатын сақтайды: артық әсер аз, айқындық көп, ал профиль алғашқы хош иістен соңғы дәмге дейін ойластырылған.",
  "Source with care": "Мұқият таңдау",
  "Roasting precision": "Қуыру дәлдігі",
  "Every roast is tuned to keep the cup transparent, balanced and exact from batch to batch.": "Әр қуыру кеседегі дәмді айқын, теңгерімді және әр партияда дәл сақтауға бапталады.",
  "We roast for structure instead of noise, shaping sweetness, acidity and body so the coffee lands with a cleaner rhythm and stronger repeatability.": "Біз тәттілік, қышқылдық пен қоюлықты қалыптастырып, кофенің құрылымы айқын әрі нәтижесі тұрақты болатындай қуырамыз.",
  "That control lets Sketo stay consistent without flattening the coffee, preserving detail while making each lot easier to understand and serve.": "Мұндай бақылау Sketo-ға кофенің ерекшелігін жоғалтпай тұрақтылық сақтауға, әр лотты түсіну мен ұсынуды жеңілдетуге мүмкіндік береді.",
  "Roast with intent": "Мақсатпен қуыру",
  "Seasonal lots": "Маусымдық лоттар",
  "The menu stays seasonal, so every lot arrives with a clear moment, a purpose and a shorter distance from harvest to cup.": "Мәзір маусымға сай жаңарып отырады, сондықтан әр лоттың өз уақыты мен мақсаты бар, ал өнім жиналғаннан кесеге жеткенге дейінгі жолы қысқа.",
  "We build the offering around fresh arrivals and real crop rhythm instead of forcing the same story all year. That keeps the coffees alive, relevant and easier to rotate.": "Ассортиментті жаңа жеткізілімдер мен нақты егін маусымына сүйеніп құрамыз. Бұл кофенің балғындығын сақтап, түрлерін уақтылы жаңартуға мүмкіндік береді.",
  "Seasonal curation also gives Sketo sharper contrast across the range: brighter filters, denser espresso profiles and a catalogue that never feels static.": "Маусымдық іріктеу Sketo ассортиментін айқындайды: жарқын сүзгі кофесі, қою эспрессо профильдері және үнемі жаңарып тұратын каталог.",
  "Season in motion": "Маусыммен бірге жаңару",
  "Consistent quality": "Тұрақты сапа",
  "Consistency is treated as part of the product, from roast calibration to service standards and repeatable brew results.": "Тұрақтылық — өнімнің бір бөлігі: қуыруды калибрлеуден сервис стандарттарына және дайындаудың қайталанатын нәтижесіне дейін.",
  "We work so the coffee reads clearly not once, but every time: stable roast curves, cleaner workflows and a service culture built around control rather than approximation.": "Кофенің дәмі әрдайым айқын болуы үшін жұмыс істейміз: тұрақты қуыру қисықтары, реттелген процестер және дәл бақылауға негізделген сервис мәдениеті.",
  "That discipline is what lets Sketo scale taste without losing character, giving partners and guests the same level of confidence in every cup.": "Осы тәртіп Sketo-ға өзіндік сипатын сақтай отырып дәм сапасын кең көлемде ұсынуға және әр кеседе серіктестер мен қонақтардың сенімін ақтауға мүмкіндік береді.",
  "Repeat with confidence": "Нәтижеге сенімді болу",
  "Ready for the next cup?": "Келесі кесеге дайынсыз ба?",
  "Explore the current lots and find the coffees shaping this season.": "Қазіргі лоттарды қарап, осы маусымның дәмін қалыптастыратын кофені табыңыз.",
  "Education": "Оқыту",
  "Community": "Қауымдастық",
  "Astana / offline": "Астана / офлайн",
  "small groups": "шағын топтар",
  "SCA mindset": "SCA қағидалары",
  "barista + home brew": "бариста + үйде дайындау"
};

export default function LocalizedText({ text }: { text: string }) {
  const [language] = usePersistentLanguage();
  return language === "kz" ? kazakh[text] ?? text : text;
}
