import type { Language } from "../components/language";

type Text = Record<Language, string>;
const t = (ru: string, kz: string, en: string): Text => ({ ru, kz, en });
type Section = { title: Text; body: Text; href?: string; link?: Text };
type Document = { slug: string; title: Text; intro: Text; sections: Section[] };

// Drafts: owner identity and commercial terms must be approved before publication as legal documents.
export const documentCopy = {
  label: t("Информация для покупателей", "Сатып алушыларға ақпарат", "Customer information"),
  home: t("На главную", "Басты бетке", "Back to home"),
  draft: t("Проект документа", "Құжат жобасы", "Draft document"),
  notice: t("Текст ожидает подтверждения владельцем Sketo. Реквизиты продавца и окончательные условия уточняются. Эта версия не является действующей публичной офертой.", "Мәтін Sketo иесінің растауын күтуде. Сатушының деректемелері мен түпкілікті шарттар нақтылануда. Бұл нұсқа қолданыстағы жария оферта емес.", "This text is awaiting approval by the owner of Sketo. Seller details and final terms are being confirmed. This version is not an active public offer."),
  contact: t("Остались вопросы?", "Сұрақтарыңыз бар ма?", "Any questions?"),
  contactBody: t("Свяжитесь с командой Sketo, чтобы уточнить информацию о товаре или вашем обращении.", "Тауар немесе өтінішіңіз туралы ақпаратты нақтылау үшін Sketo командасына хабарласыңыз.", "Contact the Sketo team for product information or help with your enquiry."),
  whatsapp: t("Написать в WhatsApp ↗", "WhatsApp арқылы жазу ↗", "Message on WhatsApp ↗"),
};

export const documents: Document[] = [
  {
    slug: "privacy",
    title: t("Политика конфиденциальности", "Құпиялылық саясаты", "Privacy policy"),
    intro: t("Какие сведения используются при посещении сайта и обращении в Sketo.", "Сайтқа кіргенде және Sketo-ға хабарласқанда қандай мәліметтер қолданылады.", "Information used when you visit this website or contact Sketo."),
    sections: [
      { title: t("Область действия", "Қолданылу аясы", "Scope"), body: t("Проект описывает текущую витрину Sketo. Личный кабинет покупателя, корзина, онлайн-оплата и бонусная программа пока не запущены. Перед их запуском политика будет дополнена. Юридическое лицо — оператор данных — должно быть указано владельцем до утверждения документа.", "Жоба Sketo-ның қазіргі каталогын сипаттайды. Сатып алушы кабинеті, себет, онлайн төлем және бонустық бағдарлама әлі іске қосылмаған. Олар іске қосылғанға дейін саясат толықтырылады. Құжат бекітілгенге дейін иесі деректер операторын көрсетуі тиіс.", "This draft covers the current Sketo catalogue. Customer accounts, a shopping cart, online payments and rewards have not launched. The policy will need updating before they launch. The owner must identify the legal data operator before approving this document.") },
      { title: t("Настройки на вашем устройстве", "Құрылғыңыздағы баптаулар", "Preferences on your device"), body: t("Сайт сохраняет выбранный язык в cookie и локальном хранилище браузера. В рамках сеанса также сохраняются поиск, фильтры и позиция прокрутки каталога. Эти настройки можно удалить через настройки браузера. Для входа сотрудников используются отдельные cookie авторизации.", "Сайт таңдалған тілді cookie мен браузердің жергілікті жадында сақтайды. Сеанс барысында каталогтағы іздеу, сүзгілер және айналдыру орны да сақталады. Оларды браузер баптауларынан жоюға болады. Қызметкерлердің кіруі үшін бөлек авторизация cookie файлдары қолданылады.", "The site saves your language in a cookie and browser local storage. Catalogue search, filters and scroll position are saved for the session. You can clear these preferences in your browser settings. Staff sign-in uses separate authentication cookies.") },
      { title: t("Обращения и внешние сервисы", "Өтініштер және сыртқы сервистер", "Enquiries and external services"), body: t("Кнопка заказа открывает WhatsApp с подготовленным сообщением; его отправку подтверждаете вы. Переданные вами имя, телефон и содержание переписки могут использоваться для ответа и согласования заказа. WhatsApp и Instagram обрабатывают данные по своим правилам. На странице контактов загружается карта Google; при её загрузке браузер обращается к Google и передаёт технические данные, включая IP-адрес.", "Тапсырыс батырмасы дайын хабарламасы бар WhatsApp-ты ашады; оны жіберуді өзіңіз растайсыз. Берген атыңыз, телефоныңыз және хат алмасу мазмұны жауап беру мен тапсырысты келісу үшін қолданылуы мүмкін. WhatsApp пен Instagram деректерді өз ережелері бойынша өңдейді. Байланыс бетінде Google картасы жүктеледі; браузер Google-ға IP мекенжайын қоса техникалық деректер жібереді.", "The order button opens WhatsApp with a prepared message; you choose whether to send it. Your name, phone number and messages may be used to reply and discuss an order. WhatsApp and Instagram apply their own privacy rules. The contact page loads a Google map, which sends technical information, including your IP address, to Google.") },
      { title: t("Запросы о данных", "Деректер туралы сұраулар", "Data enquiries"), body: t("По вопросам использования, исправления или удаления переданных сведений свяжитесь с Sketo по телефону +7 747 383 53 98. Сроки хранения, перечень обработчиков, место хранения и основания передачи данных должны быть подтверждены оператором до утверждения политики. Не отправляйте в переписке пароли, коды подтверждения и полные данные банковской карты.", "Берілген мәліметтерді пайдалану, түзету немесе жою бойынша Sketo-ға +7 747 383 53 98 нөмірімен хабарласыңыз. Сақтау мерзімін, өңдеушілерді, сақтау орнын және беру негіздерін оператор саясат бекітілгенге дейін растауы тиіс. Хат алмасуда құпиясөздерді, растау кодтарын және банк картасының толық деректерін жібермеңіз.", "For questions about use, correction or deletion of information you shared, contact Sketo at +7 747 383 53 98. Retention periods, processors, storage locations and transfer grounds must be confirmed before approval. Do not send passwords, verification codes or full card details in messages.") },
    ],
  },
  {
    slug: "offer",
    title: t("Публичная оферта", "Жария оферта", "Public offer"),
    intro: t("Проект условий приобретения кофе, аксессуаров и оборудования Sketo.", "Sketo кофесін, аксессуарларын және жабдықтарын сатып алу шарттарының жобасы.", "Draft terms for purchasing Sketo coffee, accessories and equipment."),
    sections: [
      { title: t("Статус документа и продавец", "Құжат мәртебесі және сатушы", "Document status and seller"), body: t("Этот проект не устанавливает договорные условия и не предназначен для акцепта. Sketo — название бренда; полное наименование продавца, ИИН/БИН и юридический адрес пока не подтверждены. До утверждения этих сведений и условий владельцем действующая оферта на этой странице не опубликована.", "Бұл жоба шарттық талаптарды белгілемейді және акцептеуге арналмаған. Sketo — бренд атауы; сатушының толық атауы, ЖСН/БСН және заңды мекенжайы әлі расталмаған. Иесі осы деректер мен шарттарды бекіткенге дейін бұл бетте қолданыстағы оферта жарияланбаған.", "This draft does not establish contractual terms and cannot be accepted as an offer. Sketo is a brand name; the seller’s legal name, identification number and registered address are not yet confirmed. No active offer is published here until the owner approves the details and terms.") },
      { title: t("Каталог и обращение", "Каталог және хабарласу", "Catalogue and enquiries"), body: t("На сайте можно ознакомиться с товарами и отправить запрос в WhatsApp. Переход в мессенджер сам по себе не подтверждает покупку или оплату. До согласования покупки необходимо уточнить товар, количество, наличие, итоговую стоимость и способ получения.", "Сайтта тауарларды қарап, WhatsApp арқылы сұрау жіберуге болады. Мессенджерге өту сатып алуды немесе төлемді растамайды. Сатып алуды келіспес бұрын тауарды, санын, бар-жоғын, жалпы құнын және алу тәсілін нақтылау қажет.", "You can browse products and send an enquiry through WhatsApp. Opening the messenger does not confirm a purchase or payment. Confirm the product, quantity, availability, total price and collection or delivery arrangements before purchasing.") },
      { title: t("Цена и оплата", "Баға және төлем", "Price and payment"), body: t("Цены на сайте указываются в тенге. Если цена не указана, запросите предложение у команды Sketo. Приём онлайн-платежей на сайте пока не подключён. Порядок оплаты, момент заключения договора и правила подтверждения заказа будут включены в окончательную редакцию.", "Сайттағы бағалар теңгемен көрсетіледі. Баға көрсетілмесе, Sketo командасынан ұсыныс сұраңыз. Сайттағы онлайн төлем әлі қосылмаған. Төлем тәртібі, шарт жасасу сәті және тапсырысты растау ережелері түпкілікті нұсқаға енгізіледі.", "Website prices are in tenge. If no price is listed, request a quotation from Sketo. Online payment is not yet enabled. Payment terms, contract formation and order confirmation rules will be included in the approved version.") },
      { title: t("Получение и обращения", "Тауарды алу және өтініштер", "Receiving products and getting help"), body: t("Перед покупкой уточните условия доставки, самовывоза, гарантии и возврата для выбранного товара. Для бизнес-заказов необходимо отдельно согласовать договор, спецификацию и расчёты. Опубликованный проект не ограничивает права покупателя, установленные законодательством Республики Казахстан.", "Сатып алмас бұрын таңдалған тауардың жеткізу, алып кету, кепілдік және қайтару шарттарын нақтылаңыз. Бизнес тапсырыстар үшін шартты, спецификацияны және есеп айырысуды бөлек келісу қажет. Жоба Қазақстан Республикасының заңнамасында белгіленген сатып алушы құқықтарын шектемейді.", "Confirm delivery, collection, warranty and return arrangements for your product before purchasing. Business orders require separately agreed contracts, specifications and payment terms. This draft does not limit rights granted under Kazakhstan law.") },
    ],
  },
  {
    slug: "seller",
    title: t("Реквизиты продавца", "Сатушының деректемелері", "Seller details"),
    intro: t("Sketo Coffee Company · Астана, Казахстан.", "Sketo Coffee Company · Астана, Қазақстан.", "Sketo Coffee Company · Astana, Kazakhstan."),
    sections: [
      { title: t("Кофейня и шоурум", "Кофехана және шоурум", "Coffee shop and showroom"), body: t("Астана, ул. Мухтара Ауэзова, 2. Это адрес кофейни; он не заявляется как юридический адрес продавца.", "Астана, Мұхтар Әуезов көшесі, 2. Бұл кофехананың мекенжайы; сатушының заңды мекенжайы ретінде көрсетілмейді.", "2 Mukhtar Auezov Street, Astana. This is the coffee shop address, not a confirmed registered address of the seller."), href: "https://visitastana.kz/ru/about-city/where-to-eat/sketo/", link: t("Sketo на Visit Astana ↗", "Visit Astana сайтындағы Sketo ↗", "Sketo on Visit Astana ↗") },
      { title: t("Телефон и социальные сети", "Телефон және әлеуметтік желілер", "Phone and social media"), body: t("Телефон: +7 747 383 53 98. Instagram: @sketo.coffee. По вопросам товаров и заказов можно связаться с командой в WhatsApp.", "Телефон: +7 747 383 53 98. Instagram: @sketo.coffee. Тауарлар мен тапсырыстар бойынша командаға WhatsApp арқылы хабарласуға болады.", "Phone: +7 747 383 53 98. Instagram: @sketo.coffee. Contact the team on WhatsApp for product and order enquiries."), href: "https://www.instagram.com/sketo.coffee/", link: t("Instagram Sketo ↗", "Sketo Instagram ↗", "Sketo Instagram ↗") },
      { title: t("Юридические и банковские сведения", "Заңды және банктік мәліметтер", "Legal and banking details"), body: t("Полное наименование ИП/ТОО, ИИН/БИН, юридический адрес, официальный email и банковские реквизиты ожидают подтверждения владельцем. До оплаты запросите реквизиты продавца и документы по заказу. Название бренда не заменяет сведения о юридическом продавце.", "ЖК/ЖШС толық атауы, ЖСН/БСН, заңды мекенжайы, ресми email және банк деректемелері иесінің растауын күтуде. Төлемге дейін сатушы деректемелері мен тапсырыс құжаттарын сұраңыз. Бренд атауы заңды сатушы туралы мәліметтерді алмастырмайды.", "The legal business name, identification number, registered address, official email and banking details await owner confirmation. Request seller details and order documents before payment. A brand name does not replace the legal seller’s identity.") },
    ],
  },
  {
    slug: "delivery",
    title: t("Оплата и доставка", "Төлем және жеткізу", "Payment and delivery"),
    intro: t("Как связаться с нами и согласовать получение заказа.", "Бізбен қалай хабарласып, тапсырысты алуды келісуге болады.", "How to contact us and arrange your order."),
    sections: [
      { title: t("Как заказать", "Қалай тапсырыс беруге болады", "How to enquire"), body: t("Выберите товар в каталоге и нажмите кнопку заказа через WhatsApp. Перед отправкой можно дополнить сообщение количеством и вопросами. Сам переход в WhatsApp не создаёт оплаченный заказ.", "Каталогтан тауарды таңдап, WhatsApp арқылы тапсырыс беру батырмасын басыңыз. Жібермес бұрын хабарламаға санын және сұрақтарды қоса аласыз. WhatsApp-қа өту төленген тапсырысты жасамайды.", "Choose a catalogue item and use the WhatsApp order button. Add quantities or questions before sending the message. Opening WhatsApp does not create a paid order.") },
      { title: t("Способы оплаты", "Төлем тәсілдері", "Payment methods"), body: t("Онлайн-оплата на сайте пока недоступна. Актуальный способ оплаты и итоговую сумму уточняйте у команды Sketo перед покупкой. Не отправляйте данные карты или коды из SMS в переписке.", "Сайтта онлайн төлем әзірге қолжетімсіз. Сатып алмас бұрын қолданыстағы төлем тәсілін және жалпы соманы Sketo командасынан нақтылаңыз. Хат алмасуда карта деректерін немесе SMS кодтарын жібермеңіз.", "Online payment is not yet available on this website. Confirm the payment method and total amount with Sketo before purchasing. Do not share card details or SMS codes in messages.") },
      { title: t("Доставка и самовывоз", "Жеткізу және алып кету", "Delivery and collection"), body: t("Возможность доставки по вашему адресу, её стоимость, сроки и доступность самовывоза нужно уточнить до покупки. Единые тарифы и зоны доставки пока не опубликованы. Адрес кофейни: Астана, ул. Мухтара Ауэзова, 2; перед поездкой за заказом уточните готовность товара.", "Сатып алмас бұрын мекенжайыңызға жеткізу мүмкіндігін, құнын, мерзімін және алып кету мүмкіндігін нақтылау қажет. Бірыңғай тарифтер мен жеткізу аймақтары әлі жарияланбаған. Кофехана мекенжайы: Астана, Мұхтар Әуезов көшесі, 2; тапсырысты алуға бармас бұрын тауардың дайындығын нақтылаңыз.", "Confirm delivery availability, cost, timing and collection options before purchasing. Standard delivery rates and coverage areas have not been published. The coffee shop is at 2 Mukhtar Auezov Street, Astana; confirm your order is ready before travelling.") },
      { title: t("Оборудование и B2B", "Жабдықтар және B2B", "Equipment and B2B"), body: t("Для оборудования и оптовых заказов запросите индивидуальное предложение. В нём необходимо согласовать комплектацию, цену, срок поставки, перевозку, гарантию и, при необходимости, установку. Эти услуги не считаются включёнными в цену без согласования.", "Жабдықтар мен көтерме тапсырыстар үшін жеке ұсыныс сұраңыз. Онда жиынтықты, бағаны, жеткізу мерзімін, тасымалдауды, кепілдікті және қажет болса орнатуды келісу керек. Келісілмеген қызметтер бағаға енгізілген болып саналмайды.", "Request an individual quotation for equipment and wholesale orders. Agree on specification, price, lead time, shipping, warranty and any installation. These services should not be assumed included without agreement.") },
    ],
  },
  {
    slug: "returns",
    title: t("Возврат и обмен", "Қайтару және айырбастау", "Returns and exchanges"),
    intro: t("Информация для покупателей и порядок обращения в Sketo.", "Сатып алушыларға ақпарат және Sketo-ға хабарласу тәртібі.", "Information for customers and how to contact Sketo."),
    sections: [
      { title: t("С чего начать", "Неден бастау керек", "Getting started"), body: t("Свяжитесь с командой по телефону +7 747 383 53 98 или через WhatsApp. Укажите товар, дату покупки и причину обращения. По возможности приложите фото и подтверждение покупки. Отсутствие чека само по себе не исключает возможность подтвердить покупку другими доказательствами.", "Командаға +7 747 383 53 98 нөмірімен немесе WhatsApp арқылы хабарласыңыз. Тауарды, сатып алу күнін және өтініш себебін көрсетіңіз. Мүмкіндігінше фото мен сатып алу растауын қосыңыз. Чектің болмауы сатып алуды басқа дәлелдермен растау мүмкіндігін жоққа шығармайды.", "Call +7 747 383 53 98 or contact us on WhatsApp. Include the product, purchase date and reason for your enquiry. If available, attach photos and proof of purchase. A missing receipt does not itself prevent you from proving the purchase in other ways.") },
      { title: t("Непродовольственные товары", "Азық-түлік емес тауарлар", "Non-food products"), body: t("Для непродовольственных товаров надлежащего качества законодательство РК предусматривает обмен или возврат в течение 14 календарных дней при соблюдении установленных условий и исключений. Товар должен быть неиспользованным, с сохранёнными потребительскими свойствами, товарным видом, пломбами и ярлыками. Для бизнес-покупок применяются соответствующий договор и законодательство.", "Сапалы азық-түлік емес тауарларды ҚР заңнамасында белгіленген шарттар мен ерекшеліктерді ескере отырып 14 күнтізбелік күн ішінде айырбастауға немесе қайтаруға болады. Тауар пайдаланылмаған, тұтынушылық қасиеттері, тауарлық түрі, пломбалары мен заттаңбалары сақталған болуы тиіс. Бизнес сатып алуларға тиісті шарт пен заңнама қолданылады.", "Kazakhstan law provides for exchange or return of qualifying non-food products of proper quality within 14 calendar days, subject to statutory conditions and exceptions. Products must be unused, with their properties, appearance, seals and labels preserved. Business purchases are governed by the applicable contract and law.") },
      { title: t("Кофе и товары с недостатками", "Кофе және ақаулы тауарлар", "Coffee and faulty products"), body: t("Правило возврата качественных непродовольственных товаров не распространяется на кофе как пищевой продукт. При недостатках, нарушении срока годности или несоответствии заказу сохраняются предусмотренные законом права покупателя. Сообщите о проблеме и сохраните упаковку и маркировку, если они есть: это поможет разобраться с обращением.", "Сапалы азық-түлік емес тауарларды қайтару ережесі тағам өнімі болып табылатын кофеге қолданылмайды. Ақау, жарамдылық мерзімінің бұзылуы немесе тапсырысқа сәйкессіздік болғанда сатып алушының заңда көзделген құқықтары сақталады. Мәселе туралы хабарлап, бар болса қаптама мен таңбалауды сақтаңыз: бұл өтінішті қарауға көмектеседі.", "The rule for returning non-food products of proper quality does not apply to coffee as a food product. Statutory rights remain in cases of defects, expired products or an incorrect order. Report the issue and retain packaging and labels if available to help resolve it.") },
      { title: t("Возврат денежных средств", "Ақшаны қайтару", "Refunds"), body: t("Способ возврата зависит от первоначального способа оплаты и применимых правил. Срок зачисления также зависит от банка. Условия не должны ограничивать законные права покупателя. Конкретный порядок обработки возвратов Sketo должен быть подтверждён владельцем перед утверждением документа.", "Қайтару тәсілі бастапқы төлем әдісіне және қолданылатын ережелерге байланысты. Қаражаттың түсу мерзімі банкке де байланысты. Шарттар сатып алушының заңды құқықтарын шектемеуі тиіс. Sketo қайтаруларын өңдеудің нақты тәртібін құжат бекітілгенге дейін иесі растауы тиіс.", "Refund arrangements depend on the original payment method and applicable rules. Bank processing also affects crediting times. These terms must not limit statutory rights. Sketo’s specific refund procedure requires owner confirmation before this document is approved."), href: "https://www.gov.kz/situations/464/intro?lang=ru", link: t("Разъяснения о правах потребителей ↗", "Тұтынушы құқықтары туралы түсіндірме ↗", "Consumer rights guidance ↗") },
    ],
  },
];
